#!/bin/bash
cd /lib64
ftp -nv 192.168.1.145<<EOF
user anonymous anonymous
binary
put libnetmap.so
quit
EOF

cd /usr/local/vsecplat/bin
ftp -nv 192.168.1.145<<EOF
user anonymous anonymous
binary
put vsecplat
quit
EOF

cd /usr/local/vsecplat/drv
ftp -nv 192.168.1.145<<EOF
user anonymous anonymous
binary
put netmap_lin.ko
# put e1000.ko
put virtio_net.ko
quit
EOF

