obj-$(CONFIG_NETMAP) += netmap_lin.o

netmap_lin-objs := netmap.o netmap_mem2.o \
				netmap_generic.o netmap_mbq.o netmap_vale.o \
				netmap_offloadings.o netmap_pipe.o netmap_linux.o \
				netmap_monitor.o
